/// Automatically generated by multiple_object_generater
module sample_devices (
    input wire clk,
    input wire rst_n
);

    wire [12:0] timer;

    always @(posedge clk) begin
        if (!rst_n) begin
            timer <= 0;
        end else if (timer < 2300) begin
            timer <= timer + 1;
        end
    end

    wire [127:0] chip0_rx;
    wire chip0_rx_vld;
    reg [127:0] chip0_tx;
    reg chip0_tx_vld;
    shapechangeable_chip #(
        .IS_ROOT(1),
        .RANDOM_SEED(3698505027)
    ) chip0 (
        .flit_rx(chip0_rx),
        .flit_rx_vld(chip0_rx_vld),
        .flit_tx(chip0_tx),
        .flit_tx_vld(chip0_tx_vld)
    );

    wire [127:0] chip1_rx;
    wire chip1_rx_vld;
    reg [127:0] chip1_tx;
    reg chip1_tx_vld;
    shapechangeable_chip #(
        .IS_ROOT(0),
        .RANDOM_SEED(3215388797)
    ) chip1 (
        .flit_rx(chip1_rx),
        .flit_rx_vld(chip1_rx_vld),
        .flit_tx(chip1_tx),
        .flit_tx_vld(chip1_tx_vld)
    );

    wire [127:0] chip2_rx;
    wire chip2_rx_vld;
    reg [127:0] chip2_tx;
    reg chip2_tx_vld;
    shapechangeable_chip #(
        .IS_ROOT(0),
        .RANDOM_SEED(301043392)
    ) chip2 (
        .flit_rx(chip2_rx),
        .flit_rx_vld(chip2_rx_vld),
        .flit_tx(chip2_tx),
        .flit_tx_vld(chip2_tx_vld)
    );

    wire [127:0] chip3_rx;
    wire chip3_rx_vld;
    reg [127:0] chip3_tx;
    reg chip3_tx_vld;
    shapechangeable_chip #(
        .IS_ROOT(0),
        .RANDOM_SEED(682813715)
    ) chip3 (
        .flit_rx(chip3_rx),
        .flit_rx_vld(chip3_rx_vld),
        .flit_tx(chip3_tx),
        .flit_tx_vld(chip3_tx_vld)
    );

    wire [127:0] chip4_rx;
    wire chip4_rx_vld;
    reg [127:0] chip4_tx;
    reg chip4_tx_vld;
    shapechangeable_chip #(
        .IS_ROOT(0),
        .RANDOM_SEED(129984386)
    ) chip4 (
        .flit_rx(chip4_rx),
        .flit_rx_vld(chip4_rx_vld),
        .flit_tx(chip4_tx),
        .flit_tx_vld(chip4_tx_vld)
    );
    always @(*) begin
        chip0_tx = 0;
        chip0_tx_vld = 0;
        chip1_tx = 0;
        chip1_tx_vld = 0;
        chip2_tx = 0;
        chip2_tx_vld = 0;
        chip3_tx = 0;
        chip3_tx_vld = 0;
        chip4_tx = 0;
        chip4_tx_vld = 0;
        if (0) begin
            // dummy
        end else if (timer < 200) begin
            chip0_rx = chip0_tx | chip1_tx;
            chip0_rx_vld = chip0_tx_vld | chip1_tx_vld;
            chip1_rx = chip1_tx | chip0_tx;
            chip1_rx_vld = chip1_tx_vld | chip0_tx_vld;
            chip2_rx = chip2_tx;
            chip2_rx_vld = chip2_tx_vld;
            chip3_rx = chip3_tx;
            chip3_rx_vld = chip3_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 400) begin
            chip0_rx = chip0_tx | chip1_tx;
            chip0_rx_vld = chip0_tx_vld | chip1_tx_vld;
            chip1_rx = chip1_tx | chip0_tx | chip2_tx;
            chip1_rx_vld = chip1_tx_vld | chip0_tx_vld | chip2_tx_vld;
            chip2_rx = chip2_tx | chip1_tx;
            chip2_rx_vld = chip2_tx_vld | chip1_tx_vld;
            chip3_rx = chip3_tx;
            chip3_rx_vld = chip3_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 600) begin
            chip0_rx = chip0_tx | chip1_tx;
            chip0_rx_vld = chip0_tx_vld | chip1_tx_vld;
            chip1_rx = chip1_tx | chip0_tx | chip2_tx | chip3_tx;
            chip1_rx_vld = chip1_tx_vld | chip0_tx_vld | chip2_tx_vld | chip3_tx_vld;
            chip2_rx = chip2_tx | chip1_tx;
            chip2_rx_vld = chip2_tx_vld | chip1_tx_vld;
            chip3_rx = chip3_tx | chip1_tx;
            chip3_rx_vld = chip3_tx_vld | chip1_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 1100) begin
            chip0_rx = chip0_tx | chip1_tx;
            chip0_rx_vld = chip0_tx_vld | chip1_tx_vld;
            chip1_rx = chip1_tx | chip0_tx | chip2_tx;
            chip1_rx_vld = chip1_tx_vld | chip0_tx_vld | chip2_tx_vld;
            chip2_rx = chip2_tx | chip1_tx;
            chip2_rx_vld = chip2_tx_vld | chip1_tx_vld;
            chip3_rx = chip3_tx;
            chip3_rx_vld = chip3_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 1300) begin
            chip0_rx = chip0_tx;
            chip0_rx_vld = chip0_tx_vld;
            chip1_rx = chip1_tx;
            chip1_rx_vld = chip1_tx_vld;
            chip2_rx = chip2_tx;
            chip2_rx_vld = chip2_tx_vld;
            chip3_rx = chip3_tx;
            chip3_rx_vld = chip3_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 1700) begin
            chip0_rx = chip0_tx | chip3_tx;
            chip0_rx_vld = chip0_tx_vld | chip3_tx_vld;
            chip1_rx = chip1_tx;
            chip1_rx_vld = chip1_tx_vld;
            chip2_rx = chip2_tx;
            chip2_rx_vld = chip2_tx_vld;
            chip3_rx = chip3_tx | chip0_tx;
            chip3_rx_vld = chip3_tx_vld | chip0_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else if (timer < 2300) begin
            chip0_rx = chip0_tx;
            chip0_rx_vld = chip0_tx_vld;
            chip1_rx = chip1_tx;
            chip1_rx_vld = chip1_tx_vld;
            chip2_rx = chip2_tx;
            chip2_rx_vld = chip2_tx_vld;
            chip3_rx = chip3_tx;
            chip3_rx_vld = chip3_tx_vld;
            chip4_rx = chip4_tx;
            chip4_rx_vld = chip4_tx_vld;
        end else begin
        end
    end
endmodule
